#!/usr/bin/env python3
"""Generate a static large/medium airport glyph database for ADS-B display.

Downloads OurAirports' airports.csv, filters to large_airport and
medium_airport types, and emits a compact C array of
{icao, name, lat, lon, large} for Map view glyphs and ICAO↔name lookup
(detail-card routes, location picker). Airports the user has saved as a
Location (with runway data from airportdb.io) are drawn with full runway
geometry instead — see draw_saved_airports() in map_view.cpp, which
skips any static-DB entry whose ICAO matches a saved Location.

Usage:
    python3 tools/generate_airports_db.py [--output PATH]
"""

import argparse
import csv
import io
import sys
import unicodedata
import urllib.request
from pathlib import Path

AIRPORTS_CSV_URL = "https://davidmegginson.github.io/ourairports-data/airports.csv"
INCLUDED_TYPES = {"large_airport", "medium_airport"}
# Fits detail-card / picker labels; OurAirports names are often longer.
# Byte length (ASCII after folding) including room for "...".
NAME_MAX = 31  # + NUL in char name[32]


def download_csv(url: str) -> str:
    req = urllib.request.Request(url, headers={"User-Agent": "ADS-B-Display-Airports-DB/1.0"})
    with urllib.request.urlopen(req, timeout=60) as resp:
        return resp.read().decode("utf-8")


def c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def to_ascii(s: str) -> str:
    # Montserrat has no Arabic/CJK/etc.; fold accents then drop non-ASCII.
    nk = unicodedata.normalize("NFKD", s or "")
    return "".join(c for c in nk if 32 <= ord(c) < 127)


def truncate_name(name: str) -> str:
    name = " ".join(to_ascii(name).split())  # collapse whitespace + ASCII-fold
    if len(name) <= NAME_MAX:
        return name
    budget = NAME_MAX - 3  # room for "..."
    cut = name[:budget].rsplit(" ", 1)[0]
    if len(cut) < 12:
        cut = name[:budget]
    return cut + "..."


def parse_airports(csv_text: str):
    airports = []
    reader = csv.DictReader(io.StringIO(csv_text))
    for row in reader:
        if row.get("type") not in INCLUDED_TYPES:
            continue
        icao = (row.get("ident") or "").strip()
        if not icao or len(icao) > 4:
            continue  # skip non-ICAO idents (some entries use local codes)
        try:
            lat = float(row["latitude_deg"])
            lon = float(row["longitude_deg"])
        except (KeyError, ValueError):
            continue
        # Prefer official name; fall back to municipality if blank.
        raw_name = (row.get("name") or "").strip() or (row.get("municipality") or "").strip() or icao
        airports.append({
            "icao": icao,
            "name": truncate_name(raw_name),
            "lat": lat,
            "lon": lon,
            "large": 1 if row["type"] == "large_airport" else 0,
        })
    return airports


def write_header(airports, output_path: str):
    with open(output_path, "w") as f:
        f.write("// Auto-generated static airport glyph + name DB\n")
        f.write(f"// Source: {AIRPORTS_CSV_URL}\n")
        f.write("// Generated by tools/generate_airports_db.py\n")
        f.write(f"// {len(airports)} airports (large_airport + medium_airport)\n")
        f.write("#pragma once\n\n")
        f.write("struct StaticAirport {\n")
        f.write("    char icao[5];\n")
        f.write("    char name[32]; // truncated OurAirports name\n")
        f.write("    float lat, lon;\n")
        f.write("    unsigned char large; // 1 = large_airport, 0 = medium_airport\n")
        f.write("};\n\n")
        f.write(f"#define AIRPORTS_DB_COUNT {len(airports)}\n\n")
        f.write(f"static const StaticAirport airports_db[AIRPORTS_DB_COUNT] = {{\n")
        for ap in airports:
            f.write(
                f'    {{"{ap["icao"]}", "{c_escape(ap["name"])}", '
                f'{ap["lat"]:.6f}f, {ap["lon"]:.6f}f, {ap["large"]}}},\n'
            )
        f.write("};\n")

    size_estimate = len(airports) * 48
    print(f"Wrote {len(airports)} airports to {output_path} (~{size_estimate/1024:.1f} KB)")


def main():
    parser = argparse.ArgumentParser(description="Generate static airport glyph DB for ADS-B display")
    parser.add_argument("--output", type=str, default=None,
                        help="Output path (default: src/ui/airports_db.h)")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parent.parent
    output = args.output or str(repo_root / "src" / "ui" / "airports_db.h")

    print(f"Downloading {AIRPORTS_CSV_URL} ...")
    try:
        csv_text = download_csv(AIRPORTS_CSV_URL)
    except Exception as e:
        print(f"ERROR: failed to download airports.csv: {e}", file=sys.stderr)
        sys.exit(1)

    airports = parse_airports(csv_text)
    if not airports:
        print("ERROR: no airports parsed — check the CSV format/URL", file=sys.stderr)
        sys.exit(1)

    write_header(airports, output)


if __name__ == "__main__":
    main()
